### PR TITLE
Align

### PR DESCRIPTION
**Pull request by uhuntu**

### CODE REVIEW

**Comment by kou** [comment]
Could you explain what is improved by this?
Could you rebase on master or use another branch?

**Comment by uhuntu** [comment]
Hello @kou When I installed with Redmine X UX Upgrade, seems in search box right button is bad align.

**Comment by uhuntu** [comment]
fts

**Comment by kou** [comment]
Hmm. It's not happen with normal Redmine.
Could you try normal Redmine too?

**Comment by uhuntu** [comment]
Yes, normal Redmine working fine.

**Comment by kou** [comment]
If we remove `align-items: center;`, the style works with normal Redmine and Redmine X UX Upgrade, right?

**Comment by uhuntu** [comment]
That is correct.

**Comment by kou** [comment]
OK. Then let's complete #112.

**Pull request closed without merging**
